cookie:
  expiry_days: 90
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    lorraine:
      email: wu_yumeng@icekredit.com
      logged_in: false
      name: wym
      password: $2b$12$KUhYz82QaNpPMo0zpqwW3eTCDAEm646qyzfRYCcYXHXIQECQaVbc6
    shunji:
      email: lalala@163.com
      logged_in: false
      name: shunji
      password: $2b$12$YY1thOJ.qzeEfAtW7kjB1uiHhTI859tKxljENMNmkLaVSm7UkLfzG
    stellariaperso:
      email: 18503004845@163.com
      logged_in: false
      name: Stella
      password: $2b$12$uHg4FwroKSIut2dhteeB/.C5KUFlvHeEOWsXakyC72XO27FKfQQ7m
    why:
      email: wang_haoyun@icekredit.com
      logged_in: false
      name: "\u738B\u660A\u4E91"
      password: $2b$12$f/cF.237slM7VG6ReQKoBufHl7GDtghoaKOZ1Y3V84t/qhh7pGSxK
preauthorized:
  emails:
  
